version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test --passWithNoTests
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build the app
          command: |
            npm install
            npm run build
      - run:
          name: Deploy to firebase
          command: |
            echo $SA_KEY > credentials.json
            GOOGLE_APPLICATION_CREDENTIALS=credentials.json firebase deploy
workflows:
  build-and-test:
    jobs:
      - test-node
      - build-and-deploy:
          requires:
            - test-node
