version: 2.1
orbs:
  node: circleci/node@5.2
jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: |
            npm install
            npm test --passWithNoTests
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: |
            npm i --package-lock-only
            npm install --save-dev firebase-tools
            npm run build
      - persist_to_workspace:
          root: project
          paths:
            - firebase
  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: /project
      - run:
          name: Deploy to firebase
          command: |
            echo "$SA_KEY" | base64 --decode > credentials.json
            GOOGLE_APPLICATION_CREDENTIALS=credentials.json npm exec -- /project/firebase deploy
workflows:
  build-and-test:
    jobs:
      - test-node
      - build:
          requires:
            - test-node
      # - deploy:
      #     requires:
      #       - build
