version: 2.1
orbs:
  node: circleci/node@5.2
jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: |
            npm install
            npm test --passWithNoTests
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: |
            npm i --package-lock-only
            npm install --save-dev firebase-tools
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to firebase
          command: |
            echo "$SA_KEY" | base64 --decode > credentials.json
            GOOGLE_APPLICATION_CREDENTIALS=credentials.json npm exec -- firebase deploy
workflows:
  build-and-test:
    jobs:
      - test-node
      - build:
          requires:
            - test-node
      - deploy:
          requires:
            - build
