version: 2.1
orbs:
  node: circleci/node@5.2
jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: |
            npm install
            npm test --passWithNoTests
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: |
            npm i --package-lock-only
            npm install --save-dev firebase-tools
            npm run build
            echo "$SA_KEY" | base64 --decode > credentials.json
            GOOGLE_APPLICATION_CREDENTIALS=credentials.json npm exec -- firebase deploy
workflows:
  build-and-test:
    jobs:
      - build-and-deploy:
          requires:
            - test-node
